#!/bin/bash

cript=($(curl -s https://api.coinmarketcap.com/v1/ticker/$1/ |\
jq '.[] | .symbol, .price_usd , .percent_change_1h , .percent_change_24h' |\
sed 's/"/ /g' | cut -c 1-8 ))
echo ${cript[0]} "|" ${cript[1]}"$" "|" ${cript[2]}"%" "|" ${cript[3]}"%" 
